I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/failed_rescue_scene.rpy", line 36, in script
    You "Cameron?!"
Exception: Sayer 'You' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/failed_rescue_scene.rpy", line 36, in script
    You "Cameron?!"
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 2572, in execute
    Say.execute(self)
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\taylo\OneDrive\Desktop\renpy-8.3.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'You' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
LoveBites 1.0
Thu Sep  5 19:56:59 2024
